# Generated by Django 3.2.7 on 2021-09-28 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('timestart', models.BigIntegerField()),
                ('timefinish', models.BigIntegerField()),
            ],
            options={
                'db_table': 'mdl_quiz_attempts',
                'managed': False,
            },
        ),
    ]
