# Generated by Django 3.2.7 on 2021-09-27 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=1024)),
                ('lastname', models.CharField(max_length=1024)),
                ('username', models.CharField(max_length=1024)),
                ('email', models.CharField(max_length=1024)),
                ('idnumber', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='QuizGrade',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('grade', models.IntegerField()),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='quiz.user')),
            ],
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('timestart', models.BigIntegerField()),
                ('timefinish', models.BigIntegerField()),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='quiz.user')),
            ],
        ),
    ]
