# Generated by Django 3.2.7 on 2021-09-27 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='quizattempt',
            table='mdl_quiz_attempts',
        ),
        migrations.AlterModelTable(
            name='quizgrade',
            table='mdl_quiz_grades',
        ),
        migrations.AlterModelTable(
            name='user',
            table='mdl_user',
        ),
    ]
