# Generated by Django 3.2.7 on 2021-10-01 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizgrade',
            name='grade',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='quizgrade',
            name='quiz',
            field=models.BigIntegerField(default=7168),
        ),
        migrations.AlterField(
            model_name='quizgrade',
            name='timemodified',
            field=models.IntegerField(default=1633084932),
        ),
    ]
