# Generated by Django 3.2.7 on 2021-09-28 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=1024)),
                ('lastname', models.CharField(max_length=1024)),
                ('username', models.CharField(max_length=1024)),
                ('email', models.CharField(max_length=1024)),
                ('idnumber', models.CharField(max_length=1024)),
            ],
            options={
                'db_table': 'mdl_user',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='QuizGrade',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('grade', models.FloatField()),
                ('timemodified', models.IntegerField()),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='quiz.user')),
            ],
            options={
                'db_table': 'mdl_quiz_grades',
                'managed': True,
            },
        ),
    ]
