# Generated by Django 3.2.7 on 2021-09-27 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20210927_2307'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quizattempt',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='quizgrade',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'managed': False},
        ),
    ]
