---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: qr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      nodeSelector:
        kubernetes.io/hostname: xiaomi
      containers:
        - name: postgres
          image: postgres:13
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-config
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgresdb
            - mountPath: /var/lib/postgresql/wal
              name: postgreswal
      volumes:
        - name: postgresdb
          hostPath:
            path: "/tmp/postgresql/data"
        - name: postgreswal
          hostPath:
            path: "/tmp/postgresql/wal"  

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: qr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 6379