---
apiVersion: v1
kind: ConfigMap
metadata:
  name: qr-config
  namespace: qr-reader
  labels:
    app: qr
data:
  DEBUG: "1"
  ALLOWED_HOSTS: "*"
  DJANGO_SECRET: "algo-super-secreto"
  MESSAGE_SECRET: "algo-super-secreto"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: qr-reader
  labels:
    app: postgres
data:
  POSTGRES_DB: qr
  POSTGRES_USER: qr
  POSTGRES_PASSWORD: super-secreto
