---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: qr-reader
  labels:
    app: postgres
spec:
  ports:
   - port: 5432
     targetPort: 5432
  selector:
   app: postgres

---
apiVersion: v1
kind: Service
metadata:
  name: qr-ui
  namespace: qr-reader
  labels:
    app: qr-ui
spec:
  # type: NodePort
  # externalIPs:
  #   - 127.0.0.1
  ports:
   - port: 80
     targetPort: 8000
  selector:
   app: qr-ui



