---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: qr-reader
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      nodeSelector:
        kubernetes.io/hostname: pc5752-qr1
      containers:
        - name: postgres
          image: postgres:13
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-config
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgresdb
            - mountPath: /var/lib/postgresql/wal
              name: postgreswal
      volumes:
        - name: postgresdb
          hostPath:
            path: "/srv/kubernetes/qr_reader/postgresql/data"
        - name: postgreswal
          hostPath:
            path: "/srv/kubernetes/qr_reader/postgresql/wal"

 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qr-ui
  namespace: qr-reader
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qr-ui
  template:
    metadata:
      labels:
        app: qr-ui
    spec:
      containers:
        - name: qr
          image: registry.econo.unlp.edu.ar/qr-reader:latest
          imagePullPolicy: "Always"
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: qr-config
      imagePullSecrets:
        - name: registry-econo
